# .github/workflows/fly-deploy.yml

name: Fly Deploy

on:
  push:
    # Make sure this is the branch you want to deploy from
    branches:
      - main 

jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # The corrected line is here:
      - uses: superfly/fly-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}